# Generated by Django 5.1.1 on 2024-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(max_length=20)),
                ('size', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
