# Generated by Django 5.1.1 on 2024-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accuont', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
