# Generated by Django 5.1.1 on 2024-09-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accuont', '0002_alter_user_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_images/default.png', upload_to='user_images/'),
        ),
    ]
