# Generated by Django 5.1.1 on 2024-09-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accuont', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=789, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
